//! The city dataset. data/cities.tsv is generated by src/bin/geonames_gen.rs,
//! committed, and embedded in the binary, so loading it cannot fail at runtime:
//! a malformed line means the committed file is broken and panics in dev.

const DATA: &str = include_str!("../data/cities.tsv");
const COLUMNS: usize = 7;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct City {
    pub geonameid: u32,
    /// The local name, e.g. "Sant Julià de Lòria".
    pub name: String,
    /// The same name unaccented, for typing-friendly search. The file leaves it
    /// empty when it matches `name`; here it is always filled in.
    pub asciiname: String,
    pub country: String,
    /// The state or region, empty where the dataset has no useful one.
    pub admin1: String,
    pub population: u64,
    pub timezone: String,
}

pub fn load() -> Vec<City> {
    DATA.lines()
        .enumerate()
        .filter(|(_, line)| !line.is_empty() && !line.starts_with('#'))
        .map(|(i, line)| parse(line, i + 1))
        .collect()
}

fn parse(line: &str, lineno: usize) -> City {
    let cols: Vec<&str> = line.split('\t').collect();
    assert!(
        cols.len() == COLUMNS,
        "data/cities.tsv line {lineno}: expected {COLUMNS} columns, got {}",
        cols.len()
    );

    let name = cols[1].to_string();
    let asciiname = if cols[2].is_empty() {
        name.clone()
    } else {
        cols[2].to_string()
    };
    City {
        geonameid: field(cols[0], lineno, "geonameid"),
        name,
        asciiname,
        country: cols[3].to_string(),
        admin1: cols[4].to_string(),
        population: field(cols[5], lineno, "population"),
        timezone: cols[6].to_string(),
    }
}

fn field<T: std::str::FromStr>(value: &str, lineno: usize, name: &str) -> T {
    value
        .parse()
        .unwrap_or_else(|_| panic!("data/cities.tsv line {lineno}: bad {name} {value:?}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_a_row() {
        let city = parse(
            "3039163\tSant Julià de Lòria\tSant Julia de Loria\tAndorra\tSant Julià de Lòria\t8022\tEurope/Andorra",
            1,
        );
        assert_eq!(
            city,
            City {
                geonameid: 3039163,
                name: "Sant Julià de Lòria".to_string(),
                asciiname: "Sant Julia de Loria".to_string(),
                country: "Andorra".to_string(),
                admin1: "Sant Julià de Lòria".to_string(),
                population: 8022,
                timezone: "Europe/Andorra".to_string(),
            }
        );
    }

    #[test]
    fn an_empty_asciiname_falls_back_to_the_name() {
        let city = parse("1850147\t東京\t\tJapan\tTokyo\t9733276\tAsia/Tokyo", 1);
        assert_eq!(city.name, "東京");
        assert_eq!(city.asciiname, "東京");
    }

    #[test]
    fn an_empty_admin1_stays_empty() {
        let city = parse("9179507\tMalmok\t\tAruba\t\t5637\tAmerica/Aruba", 1);
        assert!(city.admin1.is_empty());
        assert_eq!(city.country, "Aruba");
    }

    #[test]
    #[should_panic(expected = "line 7: expected 7 columns, got 3")]
    fn rejects_a_short_line() {
        parse("9179507\tMalmok\t", 7);
    }

    #[test]
    #[should_panic(expected = "line 7: bad population")]
    fn rejects_an_unparseable_number() {
        parse("9179507\tMalmok\t\tAruba\t\tmany\tAmerica/Aruba", 7);
    }

    #[test]
    fn loads_the_committed_dataset() {
        let cities = load();
        assert!(cities.len() > 60_000, "{} rows", cities.len());

        let london = cities
            .iter()
            .find(|city| city.geonameid == 2643743)
            .expect("London is in the dataset");
        assert_eq!(london.name, "London");
        assert_eq!(london.country, "United Kingdom");
        assert_eq!(london.timezone, "Europe/London");
    }
}
